
-- Supprimer et recréer la base
DROP DATABASE IF EXISTS sms;
CREATE DATABASE sms;
\c sms;

--------------------------------------------------
--Role
--------------------------------------------------
CREATE TABLE role (
    id SERIAL PRIMARY KEY,
    role VARCHAR(50) NOT NULL UNIQUE
);


--------------------------------------------------
-- Table Utilisateur
--------------------------------------------------
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    role_id INTEGER NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_users_role
        FOREIGN KEY (role_id)
        REFERENCES role(id)
);




--------------------------------------------------
-- Table Numero Expéditeur
--------------------------------------------------
CREATE TABLE numero_expediteur (
    id_numero SERIAL PRIMARY KEY,
    valeur_numero VARCHAR(20) NOT NULL UNIQUE CHECK (valeur_numero <> ''),
    date_creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

--------------------------------------------------
-- Table Infobip (API + Base URL)
-- ✅ On enlève id_numero ici
--------------------------------------------------
CREATE TABLE infobip_info (
    id SERIAL PRIMARY KEY,
    api_key VARCHAR(100) NOT NULL,
    base_url VARCHAR(150) NOT NULL,
    date_creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


--------------------------------------------------
-- Table Users Detail
--------------------------------------------------
CREATE TABLE users_detail (
    id_utilisateur INT NOT NULL,
    id_numero INT NOT NULL,
    date_creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id_utilisateur, id_numero),
    FOREIGN KEY (id_utilisateur) REFERENCES users(id),
    FOREIGN KEY (id_numero) REFERENCES numero_expediteur(id_numero)
);

--------------------------------------------------
-- Table Numéro Destinataire
--------------------------------------------------
CREATE TABLE numero_destinataire (
    id_numero SERIAL PRIMARY KEY,
    valeur_numero VARCHAR(50) NOT NULL UNIQUE CHECK (valeur_numero <> ''),
    date_creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

--------------------------------------------------
-- Table Messages
--------------------------------------------------
CREATE TABLE messages (
    id SERIAL PRIMARY KEY,
    texte TEXT NOT NULL
);

--------------------------------------------------
-- Table Plateforme
--------------------------------------------------
CREATE TABLE plateforme (
    id SERIAL PRIMARY KEY,
    nom_plateform VARCHAR(50) UNIQUE NOT NULL,
    date_creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


--------------------------------------------------
-- Table Messages envoyés (✅ correction des erreurs)
--------------------------------------------------
CREATE TABLE message_envoye (
    id SERIAL PRIMARY KEY,
    id_numero_expediteur INT NOT NULL,
    id_message INT NOT NULL,
    id_numero_destinataire INT NOT NULL,
    date_envoi TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_numero_expediteur) REFERENCES numero_expediteur(id_numero),
    FOREIGN KEY (id_message) REFERENCES messages(id),
    FOREIGN KEY (id_numero_destinataire) REFERENCES numero_destinataire(id_numero)
);
ALTER TABLE message_envoye 
ADD COLUMN infobip_message_id VARCHAR(100);
ALTER TABLE message_envoye
ALTER COLUMN id 
ADD GENERATED BY DEFAULT AS IDENTITY;



-------------------------------------------------
---MODIF
------------------------------------------------
-- 1️⃣ Modifier la table pour ajouter la colonne id_plateforme
ALTER TABLE numero_destinataire
ADD COLUMN id_plateforme INT;

ALTER TABLE numero_destinataire
ADD COLUMN id_user INT;

ALTER TABLE numero_destinataire
ADD CONSTRAINT fk_numero_user
FOREIGN KEY (id_user)
REFERENCES users(id);


-- 2️⃣ Ajouter la contrainte de clé étrangère
ALTER TABLE numero_destinataire
ADD CONSTRAINT fk_numero_destinataire_plateforme
FOREIGN KEY (id_plateforme)
REFERENCES plateforme(id)
ON DELETE SET NULL;


--------------------------------------------------
-- ✅ Relation entre Infobip et Numéro (1-N)
-- Un numero appartient à une api_key
--------------------------------------------------
ALTER TABLE numero_expediteur
ADD COLUMN id_infobip INT;

ALTER TABLE numero_expediteur
ADD CONSTRAINT fk_numero_infobip
FOREIGN KEY (id_infobip)
REFERENCES infobip_info(id)
ON DELETE SET NULL;

ALTER TABLE numero_expediteur
ADD COLUMN id_plateforme INTEGER;


ALTER TABLE numero_expediteur
ADD CONSTRAINT fk_numero_expediteur_plateforme
FOREIGN KEY (id_plateforme)
REFERENCES plateforme(id)
ON DELETE SET NULL;

--------------------------------------------------
----OTP
--------------------------------------------------
CREATE TABLE otp (
    id BIGSERIAL PRIMARY KEY,

    id_message_envoye BIGINT NOT NULL,
    
    -- Hash bcrypt du code OTP (jamais stocker le code en clair)
    code_hash VARCHAR(255) NOT NULL,

    tentative INTEGER NOT NULL DEFAULT 0,
    max_tentative INTEGER NOT NULL DEFAULT 3,

    -- Statut de l’OTP
    statut VARCHAR(20) NOT NULL
        CHECK (statut IN ('PENDING', 'VERIFIED', 'EXPIRED')),

    date_expiration TIMESTAMP NOT NULL,
    date_creation TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Relation avec la table message_envoye (si elle existe)
    CONSTRAINT fk_otp_message
        FOREIGN KEY (id_message_envoye)
        REFERENCES message_envoye(id)
        ON DELETE CASCADE
);


-----------------------------------------------------
----Detail message
-----------------------------------------------------
CREATE TABLE message_detail (
    id BIGSERIAL PRIMARY KEY,                 

    message_id VARCHAR(255) NOT NULL UNIQUE,  

    text TEXT NOT NULL,                        
    sent_at TIMESTAMP NOT NULL,               
    done_at TIMESTAMP,                        
    status_id INT NOT NULL,                   
    status_name VARCHAR(50) NOT NULL,         
    status_description TEXT,                  
    price_per_message NUMERIC(10, 4),         
    currency VARCHAR(10),                     
    date_creation TIMESTAMP NOT NULL DEFAULT NOW() 
);

-- Ajouter la colonne id_message_envoye
ALTER TABLE message_detail 
ADD COLUMN id_message_envoye INT;

-- Ajouter la contrainte de clé étrangère
ALTER TABLE message_detail
ADD CONSTRAINT fk_message_envoye 
FOREIGN KEY (id_message_envoye) REFERENCES message_envoye(id);

------------------------------------------------------
----
------------------------------------------------------
